---
# ============================================================
# Role: unix_server — vars/main.yaml
# ============================================================

# --- Usuário a ser criado ---
unix_user_name: "usr_poc_unix"
unix_user_shell: "/bin/bash"
unix_user_home: "/home/usr_poc_unix"

# --- Pasta e arquivo de relatório ---
unix_report_path: "/opt/reports/poc_hashicorp"
unix_report_file: "poc_unix_report.txt"

# --- Serviço para validar ---
unix_service_name: "sshd"

# --- Vault ---
vault_role_id: "a229d003-d76c-e60c-56a1-f9741fbb3429"
vault_secret_id: "520b7a24-c35e-f518-b92f-947d8472b0a3"
